### ISSUE TITLE
Installation of netbox_slm plugin failed

### ISSUE THREAD

**Issue by jbbenetti** [ICTU/netbox_slm#31]
Hello everyone,

I've tried to install the netbox_slm plugin. But it fails when I run ```bash docker-compose up -d```.
I've followed the instructions on netbox_slm README.md. Moreover, I use the 1.4 version of the plugin. I have created the following files in the netbox's repository.

plugin_requirements.txt
`netbox-slm`

plugins.py
```python
PLUGINS = ["netbox_slm"]
```
docker-compose.override.yml
```yaml
version: '3.4' # This is NOT the version of NetBox! No need to adjust :)
services:
  netbox:
    image: netbox:latest-plugins
    ports:
      - 8000:8080
    build:
      context: .
      dockerfile: Dockerfile-Plugins
  netbox-worker:
    image: netbox:latest-plugins
    build:
      context: .
      dockerfile: Dockerfile-Plugins
  netbox-housekeeping:
    image: netbox:latest-plugins
    build:
      context: .
      dockerfile: Dockerfile-Plugins
```
Dockerfile-Plugins
```
FROM netboxcommunity/netbox:v3.6-2.7.0 //last version of netbox

COPY ./plugin_requirements.txt /opt/netbox/
RUN /opt/netbox/venv/bin/pip install  --no-warn-script-location -r /opt/netbox/plugin_requirements.txt

# These lines are only required if your plugin has its own static files.
COPY configuration/configuration.py /etc/netbox/config/configuration.py
COPY configuration/plugins.py /etc/netbox/config/plugins.py
RUN SECRET_KEY="dummydummydummydummydummydummydummydummydummydummy" /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py collectstatic --no-input
```

The build works.
I have the following logs : 

`netbox-docker-netbox-1       | **ImportError: cannot import name 'DynamicModelChoiceField'** from 'utilities.forms' (/opt/netbox/netbox/utilities/forms/__init__.py)`

How can I resolve this issue ?
